version: "2"
services:
  web:
    build: server/.
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy

    command: bash -c "python build_db.py && uvicorn run:app --proxy-headers --host 0.0.0.0 --port 8000"

  db:
    image: postgres
    env_file:
      - ".env"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
