export const NAV = {
  active: "Активный",
  funding: "Финансирование",
  significance: "Значимость",
  ftp_federal_target_program: "ФЦП (федеральная целевая программа)",
  actions_with_an_object: "Действия с объектом",
};

export const NAMES = {
  Y: "Да",
  N: "Нет",
  funding: "Финансирование",
  id: "id",
  objectname: "Название",
  title_in_english: "Название (in english)",
  active: "Активный",
  short_description: "Краткое описание",
  detailed_description: "Детальное описание",
  brief_description: "Краткое описание (in english)",
  detailed_description_in_english: "Детальное описание (in english)",
  mo: "МО",
  subject_of_the_federation: "Субъект федерации",
  significance: "Значимость",
  locality: "Населённый пункт",
  locality_in_english: "Населённый пункт (in english)",
  addr: "Адрес",
  addr_in_english: "Адрес (in english)",
  oktmo: "ОКТМО",
  ftp_federal_target_program: "ФЦП (федеральная целевая программа)",
  actions_with_an_object: "Действия с объектом",
  start_date_of_construction_reconstruction:
    "Дата начала строительства / реконструкции",
  date_of_completion_of_construction_reconstruction:
    "Дата завершения строительства / реконструкции",
  total_funding: "Общий объём финансирования",
  funding_from_the_federal_budget: "Финансирование из федерального бюджета",
  funding_from_the_federal_budget_of_which_mastered:
    "Финансирование из федерального бюджета (из них освоено)",
  funding_from_the_budget_of_the_subject_of_the_federation:
    "Финансирование из бюджета субъекта федерации",
  funding_from_the_budget_of_the_subject_of_the_federation_of_whi:
    "Финансирование из бюджета субъекта федерации (из них освоено)",
  funding_from_the_budget_of_the_municipality:
    "Финансирование из бюджета муниципального образования",
  funding_from_the_budget_of_the_municipality_of_which_mastered:
    "Финансирование из бюджета муниципального образования (из них освоено)",
  funding_from_extrabudgetary_sources:
    "Финансирование из внебюджетных источников",
  funding_from_extrabudgetary_sources_of_which_mastered:
    "Финансирование из внебюджетных источников (из них освоено)",
  key_or_not: "Ключевой или нет?",
  supervisory_body: "Курирующий орган",
  supervising_body_in_english: "Курирующий орган (in english)",
  address_of_the_supervising_body: "Адрес курирующего органа",
  address_of_the_supervising_body_in_english:
    "Адрес курирующего органа (in english)",
  phone_number_of_the_supervising_body: "Телефон курирующего органа",
  contact_phone_number_of_the_object: "Контактный телефон объекта",
  opening_hours_mon_fri: "Режим работы Пн.-Пт.",
  opening_hours_sat: "Режим работы Сб.",
  opening_hours_sun: "Режим работы Вс.",
  square: "Площадь",
  email: "E-mail",
  site_url: "URL сайта",
  registered: "Внесён в реестр?",
  type_of_sports_complex: "Тип спортивного комплекса",
  what_competitions_are_held: "Какие соревнования проводятся?",
  kinds_of_sports: "Виды спорта",
  yandex_object_coordinate_x: "Яндекс координата объекта X",
  yandex_object_coordinate_y: "Яндекс координата объекта Y",
  yandex_map_scale: "Маштаб Яндекс-карты",
  yandex_coordinate_center_x: "Яндекс координата центра X",
  yandex_y_center_coordinate: "Яндекс координата центра Y",
  mini_x_coordinate: "Мини координата X",
  mini_y_coordinate: "Мини координата Y",
  general_plan: "Генеральный план",
  additional_plans: "Дополнительные планы",
  photo: "Фото",
  object_gallery_url: "URL фото галереи объекта",
  video: "Видео",
  panoramas: "Панорамы",
  webcasts: "Web-трансляции",
  other_materials: "Прочие материалы",
};
